test-web/src/main/java/testas/mbeans/ReportsController.java
package testas.mbeans;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

import testas.entities.Game;
import testas.entities.LeagueEntity;
import testas.entities.PlayerEntity;
import testas.entities.TeamEntity;
import testas.services.LeagueEntityFacadeLocal;
import testas.services.PlayerEntityFacadeLocal;
import testas.services.TeamEntityFacadeLocal;

@Named("reportsController")
@RequestScoped
public class ReportsController {
	@EJB
	private PlayerEntityFacadeLocal playerFacade;
	@EJB
	private TeamEntityFacadeLocal teamFacade;
	@EJB
	private LeagueEntityFacadeLocal leagueFacade;
	
	public List<PlayerEntity> getBasketballTop10Players() {
		return playerFacade.topPlayers(Game.BASKETBALL, 10);
	}
	public List<TeamEntity> getBasketballTop10Teams() {
		return teamFacade.topTeams(Game.BASKETBALL, 10);
	}
	public List<LeagueEntity> getBasketballTop10Leagues() {
		return leagueFacade.getTopLeagues(Game.BASKETBALL, 10);
	}

	public List<PlayerEntity> getFootballTop10Players() {
		return playerFacade.topPlayersByAvg(Game.FOOTBALL, 10);
	}
	public List<TeamEntity> getFootballTop10Teams() {
		return teamFacade.topTeamsByAvg(Game.FOOTBALL, 10);
	}
	public List<LeagueEntity> getFootballTop10Leagues() {
		return leagueFacade.getTopLeaguesByAvg(Game.FOOTBALL, 10);
	}
}

test-web/src/main/webapp/reports/BasketballTop10Leagues.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<ui:composition template="/reportTemplate.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.BasketballTop10Leagues}"></h:outputText>
	</ui:define>
	<ui:define name="body">
	<h:dataTable value="#{reportsController.basketballTop10Leagues}" var="item">
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_name}"/></f:facet>
			<h:outputText value="#{item.name}"/>
		</h:column>
	</h:dataTable>
	</ui:define>
</ui:composition>
</html>

test-web/src/main/webapp/reports/BasketballTop10Players.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<ui:composition template="/reportTemplate.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.BasketballTop10Players}"></h:outputText>
	</ui:define>
	<ui:define name="body">
	<h:dataTable value="#{reportsController.basketballTop10Players}" var="item">
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_firstName}"/></f:facet>
			<h:outputText value="#{item.firstName}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_lastName}"/></f:facet>
			<h:outputText value="#{item.lastName}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_team}"/></f:facet>
			<h:outputText value="#{item.team.name}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_position}"/></f:facet>
			<h:outputText value="#{bundle[item.position]}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_playedGames}"/></f:facet>
			<h:outputText value="#{item.playedGames}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_points}"/></f:facet>
			<h:outputText value="#{item.points}"/>
		</h:column>
	</h:dataTable>
	</ui:define>
</ui:composition>
</html>

test-web/src/main/webapp/reports/BasketballTop10Teams.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<ui:composition template="/reportTemplate.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.BasketballTop10Teams}"></h:outputText>
	</ui:define>
	<ui:define name="body">
	<h:dataTable value="#{reportsController.basketballTop10Teams}" var="item">
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_name}"/></f:facet>
			<h:outputText value="#{item.name}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_playedGames}"/></f:facet>
			<h:outputText value="#{item.playedGames}"/>
		</h:column>
	</h:dataTable>
	</ui:define>
</ui:composition>
</html>

test-web/src/main/webapp/reports/FootballTop10Leagues.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<ui:composition template="/reportTemplate.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.FootballTop10Leagues}"></h:outputText>
	</ui:define>
	<ui:define name="body">
	<h:dataTable value="#{reportsController.footballTop10Leagues}" var="item">
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_name}"/></f:facet>
			<h:outputText value="#{item.name}"/>
		</h:column>
	</h:dataTable>
	</ui:define>
</ui:composition>
</html>

test-web/src/main/webapp/reports/FootballTop10Players.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<ui:composition template="/reportTemplate.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.FootballTop10Players}"></h:outputText>
	</ui:define>
	<ui:define name="body">
	<h:dataTable value="#{reportsController.footballTop10Players}" var="item">
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_firstName}"/></f:facet>
			<h:outputText value="#{item.firstName}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_lastName}"/></f:facet>
			<h:outputText value="#{item.lastName}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_team}"/></f:facet>
			<h:outputText value="#{item.team.name}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_position}"/></f:facet>
			<h:outputText value="#{bundle[item.position]}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_playedGames}"/></f:facet>
			<h:outputText value="#{item.playedGames}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_points}"/></f:facet>
			<h:outputText value="#{item.points}"/>
		</h:column>
	</h:dataTable>
	</ui:define>
</ui:composition>
</html>

test-web/src/main/webapp/reports/FootballTop10Teams.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<ui:composition template="/reportTemplate.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.FootballTop10Teams}"></h:outputText>
	</ui:define>
	<ui:define name="body">
	<h:dataTable value="#{reportsController.footballTop10Teams}" var="item">
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_name}"/></f:facet>
			<h:outputText value="#{item.name}"/>
		</h:column>
		<h:column>
			<f:facet name="header"><h:outputText value="#{bundle.Title_playedGames}"/></f:facet>
			<h:outputText value="#{item.playedGames}"/>
		</h:column>
	</h:dataTable>
	</ui:define>
</ui:composition>
</html>