test-web/src/main/java/testas/mbeans/EntityController.java
package testas.mbeans;

import java.io.Serializable;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.DataModel;

import org.primefaces.context.RequestContext;
import org.primefaces.event.SelectEvent;

import testas.entities.EntityId;
import testas.mbeans.util.EntitiesDataModel;
import testas.mbeans.util.JsfUtil;
import testas.services.EntityFacadeLocal;

public abstract class EntityController<T extends EntityId> implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7791111183104724547L;

	private static final Logger LOGGER = Logger.getLogger(EntityController.class.getName());

	private static final ResourceBundle BUNDLE = ResourceBundle.getBundle("/Bundle");

	private EntitiesDataModel<T> items = null;
	private final Class<T> entityClass;

	private int selectedItemIndex;

	private boolean inlineEditingEnabled = false;

	private T selected;
	private T editing;

	public EntityController(Class<T> entityClass) {
		this.entityClass = entityClass;
	}

	// State properties

	public T getSelected() {
		// if (current == null) {
		// current = newEntityInstance();
		// }
		return selected;
	}

	public void setSelected(T newVal) {
		selected = newVal;
	}

	public boolean isEmptySelection() {
		return selected == null;
	}

	public boolean isSelectionEmpty() {
		return getSelected() == null || getSelected().getId() == null;
	}

	public boolean isInlineEditingEnabled() {
		return inlineEditingEnabled;
	}

	public void setInlineEditingEnabled(boolean inlineEditingEnabled) {
		this.inlineEditingEnabled = inlineEditingEnabled;
	}

	public T getEntity(java.lang.Long id) {
		return getFacade().find(id);
	}

	public DataModel<T> getItems() {
		if (items == null) {
			items = new EntitiesDataModel<T>(getFacade());
			if (selectedItemIndex >= 0)
				items.setRowIndex(selectedItemIndex);
		}
		return items;
	}

	public T getEditing() {
		return editing;
	}

	public void setEditing(T editing) {
		this.editing = editing;
	}

	// Actions
	public String prepareList() {
		if (editing!=null) editing = null;
		recreateModel();
		return "List";
	}

	public String prepareView() {
		return "View";
	}

	public String prepareCreate() {
//		setSelected();
		setEditing(newEntityInstance());
		return "Create";
	}
	public String prepareEdit() {
		setEditing(getSelected());
		return "Edit";
	}

	public void prepareInlineCreate() {
		setSelected(newEntityInstance());
		setEditing(getSelected());
		items = new EntitiesDataModel<T>(getEditing(), getFacade());
		items.setRowIndex(0);
		inlineEditingEnabled = true;
	}
	public void prepareInlineEdit() {
		setEditing(getSelected());
		inlineEditingEnabled = true;
		
	}


	public String create() {
		return createEntity() ? prepareCreate() : null;
	}


	public String update() {
		return updateEntity() ? "View" : null;
	}

	public String destroy() {
		performDestroy();
		recreateModel();
		return "List";
	}

	public String destroyAndView() {
		selectedItemIndex = items.getRowIndex();
		performDestroy();
		recreateModel();
		updateCurrentItem();
		if (selectedItemIndex >= 0) {
			return "View";
		} else {
			// all items were removed - go back to list
			recreateModel();
			return "List";
		}
	}

	private void performDestroy() {
		try {
			getFacade().remove(selected);
			JsfUtil.addSuccessMessage(BUNDLE.getString(entityClass.getSimpleName() + "Deleted"));
		} catch (Exception e) {
			JsfUtil.addErrorMessage(e, BUNDLE.getString("PersistenceErrorOccured"));
		}
	}

	private void updateCurrentItem() {
		int count = getFacade().count();
		if (selectedItemIndex >= count) {
			// selected index cannot be bigger than number of items:
			selectedItemIndex = count - 1;
		}
		if (items != null) {
			items.setRowIndex(selectedItemIndex);
		}
		setSelected(selectedItemIndex >= 0
				? getFacade().findRange(selectedItemIndex, 1).get(0)
				: null);
	}

	

	public void cancelInlineEdits() {
		if (getEditing() != null && (getEditing().getId() == null || -1l == getEditing().getId())) {
			recreateModel();
		}
		setEditing(null);
		inlineEditingEnabled = false;
		JsfUtil.addSuccessMessage(BUNDLE.getString(entityClass.getSimpleName()),
				BUNDLE.getString(entityClass.getSimpleName() + "Canceled"));
	}

	public void updateInlineEdits() {
		boolean isNew = isNewEditingItem();
		boolean updated = isNew ? createEntity() : updateEntity();
		if (updated) {
			if (isNew)
				recreateModel();
			inlineEditingEnabled = false;
		} else {
			selected = getEditing();
			inlineEditingEnabled = true;
		}
	}
	
	public void refresh() {
		setSelected(null);
		recreateModel();
	}

	// Event callbacks

	public void onRowSelect(SelectEvent event) {
		if (inlineEditingEnabled) {
			RequestContext.getCurrentInstance().execute("PF('rowEditingConfirm').show();");
			inlineEditingEnabled = false;
		}
	}

	// Utility methods
	public boolean isNewEditingItem() {
		return getEditing().getId() == null || getEditing().getId() < 0;
	}

	protected boolean createEntity() {
		try {
			if (getEditing().getId() != null)
				getEditing().setId(null);
			getFacade().create(getEditing());
			JsfUtil.addSuccessMessage(BUNDLE.getString(entityClass.getSimpleName()),
					BUNDLE.getString(entityClass.getSimpleName() + "Created"));
			return true;
		} catch (Exception e) {
			JsfUtil.addErrorMessage(e, BUNDLE.getString("PersistenceErrorOccured"));
			return false;
		}
	}

	public boolean updateEntity() {
		try {
			getFacade().edit(getEditing());
			JsfUtil.addSuccessMessage(BUNDLE.getString(entityClass.getSimpleName()),
					BUNDLE.getString(entityClass.getSimpleName() + "Updated"));
			return true;
		} catch (Exception e) {
			JsfUtil.addErrorMessage(e, BUNDLE.getString("PersistenceErrorOccured"));
			return false;
		}
	}

	private void recreateModel() {
		items = null;
	}

	public boolean inlineEditable(T item) {
		return selected != null && item != null && inlineEditingEnabled && item.getId() != null
				&& item.getId().equals(selected.getId());
	}

	public boolean inlineNewEditable(T item) {
		return selected != null && item != null && inlineEditingEnabled && item.getId() != null
				&& item.getId().equals(selected.getId()) && -1l == item.getId();
	}

	protected T newEntityInstance() {
		try {
			T ret = entityClass.newInstance();
			ret.setId(-1l);
			return ret;
		} catch (InstantiationException ex) {
			LOGGER.log(Level.SEVERE, null, ex);
			throw new RuntimeException(ex);
		} catch (IllegalAccessException ex) {
			LOGGER.log(Level.SEVERE, null, ex);
			throw new RuntimeException(ex);
		}
	}

	protected abstract EntityFacadeLocal<T> getFacade();

	// Converter for entity 
	public static class EntityControllerConverter implements Converter {

		private final String entityControllerName;

		public EntityControllerConverter(String entityControllerName) {
			this.entityControllerName = entityControllerName;
		}

		@Override
		public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
			if (value == null || value.length() == 0) {
				return null;
			}

			@SuppressWarnings("rawtypes")
			EntityController controller = (EntityController) facesContext.getApplication().getELResolver()
					.getValue(facesContext.getELContext(), null, entityControllerName);
			if ("-1".equals(value)) {
				System.out.println("Retrieving selection for -1");
				Thread.dumpStack();
			}
			return controller.getEntity(getKey(value));
		}

		java.lang.Long getKey(String value) {
			java.lang.Long key;
			key = Long.valueOf(value);
			return key;
		}

		String getStringKey(java.lang.Long value) {
			return Long.toString(value, 10);
		}

		@Override
		public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
			if (object == null) {
				return null;
			}
			if (object instanceof EntityId) {
				EntityId o = (EntityId) object;
				return getStringKey(o.getId());
			} else if (object instanceof Long) {
				Long l = ((Long) object);
				return Long.toString(l, 10);
			} else {
				throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName()
						+ "; expected type: " + EntityId.class.getName());
			}
		}

	}

}

test-web/src/main/java/testas/mbeans/PlayerEntityController.java
package testas.mbeans;

import java.util.Collections;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.convert.FacesConverter;
import javax.inject.Named;

import testas.entities.Game;
import testas.entities.PlayerEntity;
import testas.entities.Position;
import testas.entities.TeamEntity;
import testas.services.PlayerEntityFacadeLocal;
import testas.services.TeamEntityFacadeLocal;

@Named("playerEntityController")
@SessionScoped
public class PlayerEntityController extends EntityController<PlayerEntity> {
	/**
	 * 
	 */
	private static final long serialVersionUID = 2335722051700992731L;
	@EJB
	private PlayerEntityFacadeLocal ejbFacade;

	@EJB
	private TeamEntityFacadeLocal teamsFacade;

	public PlayerEntityController() {
		super(PlayerEntity.class);
	}

	protected PlayerEntityFacadeLocal getFacade() {
		return ejbFacade;
	}

	@FacesConverter(forClass = PlayerEntity.class)
	public static class PlayerEntityControllerConverter extends EntityControllerConverter {

		public PlayerEntityControllerConverter() {
			super("playerEntityController");
		}
	}

	public List<Position> getPossiblePositions() {
		return Position.positions(getEditing().getGame());
	}

	public List<TeamEntity> getPossibleTeams() {
		final Game game = getEditing().getGame();
		return game != null ? teamsFacade.teamsForGame(game) : Collections.<TeamEntity> emptyList();
	}

	public int getMaxPlayedGames() {
		return getEditing().getTeam() != null ? getEditing().getTeam().getPlayedGames() : 0;
	}
}

test-web/src/main/webapp/playerEntity/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/template.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.CreatePlayerEntityTitle}"></h:outputText>
	</ui:define>
	<ui:define name="body">
		<h:form>
			<p:growl id="growl" showDetail="true" sticky="false" />
			<p:toolbar>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:button outcome="/index" value="#{bundle.IndexLink}" />
					<p:commandButton action="#{playerEntityController.prepareList}"
						value="#{bundle.ShowAllLink}" immediate="true" json="false" />
				</p:toolbarGroup>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:commandButton action="#{playerEntityController.create}"
						value="#{bundle.SaveLink}" json="false" process="@all"
						update="@form" />
				</p:toolbarGroup>
			</p:toolbar>
			<h:panelGrid columns="2">
				<p:outputLabel value="#{bundle.Label_firstName}"
					for="firstName" />
				<p:inputText id="firstName"
					value="#{playerEntityController.editing.firstName}"
					title="#{bundle.Title_firstName}" required="true"
					requiredMessage="#{bundle.RequiredMessage_firstName}" >
					<f:ajax event="change" update="@form" render="@form" />
				</p:inputText>

				<p:outputLabel value="#{bundle.Label_lastName}"
					for="lastName" />
				<p:inputText id="lastName"
					value="#{playerEntityController.editing.lastName}"
					title="#{bundle.Title_lastName}" required="true"
					requiredMessage="#{bundle.RequiredMessage_lastName}" >
					<f:ajax event="change" update="@form" render="@form" />
				</p:inputText>

				<p:outputLabel value="#{bundle.Label_game}"
					for="game" />
				<p:selectOneMenu id="game"
					value="#{playerEntityController.editing.game}"
					title="#{bundle.Title_game}" required="true"
					requiredMessage="#{bundle.RequiredMessage_game}">
					<f:selectItem itemLabel="#{bundle.SelectGameType}" itemValue="" />
					<f:selectItem itemLabel="#{bundle.BASKETBALL}"
						itemValue="BASKETBALL" />
					<f:selectItem itemLabel="#{bundle.FOOTBALL}" itemValue="FOOTBALL" />
					<f:ajax event="change" update="@form" render="@form" />
				</p:selectOneMenu>


				<p:outputLabel value="#{bundle.Label_position}"
					for="position" />
				<p:selectOneMenu id="position"
					value="#{playerEntityController.editing.position}"
					disabled="#{playerEntityController.editing.game == null}"
					title="#{bundle.Title_position}" required="true"
					requiredMessage="#{bundle.RequiredMessage_position}">
					<f:selectItem itemLabel="#{bundle.ChoosePlayerPosition}"
						itemValue="" />
					<f:selectItems
						value="#{playerEntityController.possiblePositions}" var="pitem"
						itemLabel="#{bundle[pitem]}" itemValue="#{pitem}" />
					<f:ajax event="change" update="@form" render="@form" />
				</p:selectOneMenu>

				<p:outputLabel value="#{bundle.Label_team}"
					for="team" />
				<p:selectOneMenu id="team"
					value="#{playerEntityController.editing.team}"
					disabled="#{playerEntityController.editing.game == null}"
					title="#{bundle.Title_team}">
					<f:selectItem itemLabel="#bundle.ChooseTeam" />
					<f:selectItems value="#{playerEntityController.possibleTeams}"
						var="pitem" itemLabel="#{pitem.name}" itemValue="#{pitem}" />
					<f:ajax event="change" update="@form" render="@form" />
				</p:selectOneMenu>

				<p:outputLabel value="#{bundle.Label_playedGames}"
					for="playedGames" />
				<p:spinner id="playedGames"
					value="#{playerEntityController.editing.playedGames}"
					title="#{bundle.Title_playedGames}"
					min="0" max="#{playerEntityController.maxPlayedGames}" 
					disabled="#{playerEntityController.editing.team == null || playerEntityController.editing.team.playedGames == 0}">
					<f:ajax event="change" update="@form" render="@form" />
				</p:spinner>


				<p:outputLabel value="#{bundle.Label_points}"
					for="points" />
				<p:spinner id="points"
					value="#{playerEntityController.editing.points}"
					title="#{bundle.Title_points}"  min="0"
					disabled="#{playerEntityController.editing.playedGames==0}">
					<f:ajax event="change" update="@form" render="@form" />
				</p:spinner>
				
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

</html>

test-web/src/main/webapp/playerEntity/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/template.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.ListPlayerEntityTitle}"></h:outputText>
	</ui:define>
	<ui:define name="body">
		<h:form styleClass="jsfcrud_list_form" id="form">
			<p:growl id="growl" showDetail="true" sticky="false" />
			<p:toolbar id="workGroupToolbar">
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:button outcome="/index" value="#{bundle.IndexLink}" />
				</p:toolbarGroup>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:commandButton action="#{playerEntityController.prepareView}"
						value="#{bundle.ViewLink}" ajax="false"
						disabled="#{playerEntityController.selectionEmpty || playerEntityController.inlineEditingEnabled}" />

					<p:commandButton action="#{playerEntityController.prepareCreate}"
						value="#{bundle.CreateLink}" ajax="false"
						disabled="#{playerEntityController.inlineEditingEnabled}" />


					<p:commandButton action="#{playerEntityController.prepareEdit}"
						value="#{bundle.EditLink}" ajax="false"
						disabled="#{playerEntityController.selectionEmpty || playerEntityController.inlineEditingEnabled}" />


					<p:commandButton action="#{playerEntityController.destroy}"
						value="#{bundle.DestroyLink}" ajax="false" update="growl"
						disabled="#{playerEntityController.selectionEmpty || playerEntityController.inlineEditingEnabled}" />

				</p:toolbarGroup>
				<p:toolbarGroup id="inlineToolbarGroup">
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:commandButton
						action="#{playerEntityController.prepareInlineCreate}"
						disabled="#{playerEntityController.inlineEditingEnabled}"
						value="#{bundle.CreateInlineLink}" ajax="true"
						update="datatable workGroupToolbar" />
					<p:commandButton
						action="#{playerEntityController.prepareInlineEdit}"
						value="#{bundle.EditInlineLink}"
						disabled="#{playerEntityController.selectionEmpty || playerEntityController.inlineEditingEnabled}"
						update="datatable workGroupToolbar" />
					<p:commandButton
						action="#{playerEntityController.cancelInlineEdits}"
						value="#{bundle.CancelInlineLink}" immediate="true"
						disabled="#{!playerEntityController.inlineEditingEnabled}"
						update="workGroupToolbar growl datatable" />
					<p:commandButton
						action="#{playerEntityController.updateInlineEdits}"
						value="#{bundle.UpdateInlineLink}"
						disabled="#{!playerEntityController.inlineEditingEnabled}"
						update="workGroupToolbar growl datatable" />
				</p:toolbarGroup>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:commandButton action="#{playerEntityController.refresh}"
						value="#{bundle.RefreshLink}" update="workGroupToolbar datatable"
						disabled="#{playerEntityController.inlineEditingEnabled}" />
				</p:toolbarGroup>

			</p:toolbar>

			<h:panelGroup>
				<p:dataTable id="datatable" widgetVar="datatable"
					value="#{playerEntityController.items}" var="item"
					selection="#{playerEntityController.selected}"
					selectionMode="single" rows="10" paginator="true" lazy="true"
					paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
					rowsPerPageTemplate="5,10,15">
					<p:ajax event="rowSelect"
						listener="#{playerEntityController.onRowSelect}"
						update=":form:workGroupToolbar, :form:datatable" />

					<p:column headerText="#{bundle.Title_id}">
						<h:outputText value="#{item.id}"
							rendered="#{!playerEntityController.inlineNewEditable(item)}" />
					</p:column>
					<p:column headerText="#{bundle.Title_firstName}">
						<h:outputText value="#{item.firstName}"
							rendered="#{!playerEntityController.inlineEditable(item)}" />
						<p:inputText value="#{playerEntityController.editing.firstName}"
							rendered="#{playerEntityController.inlineEditable(item)}"
							title="#{bundle.Title_firstName}" required="true"
							requiredMessage="#{bundle.RequiredMessage_firstName}">
							<f:ajax event="change" update="@form" render="@form" />
						</p:inputText>
					</p:column>
					<p:column headerText="#{bundle.Title_lastName}">
						<h:outputText value="#{item.lastName}"
							rendered="#{!playerEntityController.inlineEditable(item)}" />
						<p:inputText value="#{playerEntityController.editing.lastName}"
							rendered="#{playerEntityController.inlineEditable(item)}"
							title="#{bundle.Title_lastName}" required="true"
							requiredMessage="#{bundle.RequiredMessage_lastName}">
							<f:ajax event="change" update="@form" render="@form" />
						</p:inputText>

					</p:column>
					<p:column headerText="#{bundle.Title_game}">
						<h:outputText value="#{bundle[item.game]}"
							rendered="#{!playerEntityController.inlineNewEditable(item)}" />
						<p:selectOneMenu id="game"
							rendered="#{playerEntityController.inlineNewEditable(item)}"
							value="#{playerEntityController.editing.game}"
							title="#{bundle.Title_game}" required="true"
							requiredMessage="#{bundle.RequiredMessage_game}">
							<f:selectItem itemLabel="#{bundle.SelectGameType}" itemValue="" />
							<f:selectItem itemLabel="#{bundle.BASKETBALL}"
								itemValue="BASKETBALL" />
							<f:selectItem itemLabel="#{bundle.FOOTBALL}" itemValue="FOOTBALL" />
							<f:ajax event="change" update="@form" render="@form" />
						</p:selectOneMenu>

					</p:column>
					<p:column headerText="#{bundle.Title_position}">
						<h:outputText value="#{bundle[item.position]}"
							rendered="#{!playerEntityController.inlineEditable(item)}" />
						<p:selectOneMenu id="position_select"
							value="#{playerEntityController.editing.position}"
							disabled="#{playerEntityController.editing.game == null}"
							rendered="#{playerEntityController.inlineEditable(item)}"
							title="#{bundle.Title_position}" required="true"
							requiredMessage="#{bundle.RequiredMessage_position}">
							<f:selectItem itemLabel="#{bundle.ChoosePlayerPosition}"
								itemValue="" />
							<f:selectItems
								value="#{playerEntityController.possiblePositions}" var="pitem"
								itemLabel="#{bundle[pitem]}" itemValue="#{pitem}" />
							<f:ajax event="change" update="@form" render="@form" />
						</p:selectOneMenu>
					</p:column>
					<p:column headerText="#{bundle.Title_team}">
						<h:outputText value="#{item.team}"
							rendered="#{!playerEntityController.inlineEditable(item)}" />

						<p:selectOneMenu id="team_select"
							value="#{playerEntityController.editing.team}"
							disabled="#{playerEntityController.editing.game == null}"
							rendered="#{playerEntityController.inlineEditable(item)}"
							title="#{bundle.Title_team}">
							<f:selectItem itemLabel="#bundle.ChooseTeam" />
							<f:selectItems value="#{playerEntityController.possibleTeams}"
								var="pitem" itemLabel="#{pitem.name}" itemValue="#{pitem}" />
							<f:ajax event="change" update="@form" render="@form" />
						</p:selectOneMenu>
					</p:column>
					<p:column headerText="#{bundle.Title_playedGames}">
						<h:outputText value="#{item.playedGames}"
							rendered="#{!playerEntityController.inlineEditable(item)}" />
						<p:spinner id="playedGames_select"
							value="#{playerEntityController.editing.playedGames}"
							rendered="#{playerEntityController.inlineEditable(item)}" min="0"
							max="#{playerEntityController.maxPlayedGames}"
							disabled="#{playerEntityController.editing.team == null || playerEntityController.editing.team.playedGames == 0}">
							<f:ajax event="change" update="@form" render="@form" />
						</p:spinner>
					</p:column>
					<p:column headerText="#{bundle.Title_points}">
						<h:outputText value="#{item.points}"
							rendered="#{!playerEntityController.inlineEditable(item)}" />
						<p:spinner id="points_select"
							value="#{playerEntityController.editing.points}" min="0"
							rendered="#{playerEntityController.inlineEditable(item)}"
							disabled="#{playerEntityController.editing.playedGames==0}">
							<f:ajax event="change" update="@form" render="@form" />
						</p:spinner>

					</p:column>
				</p:dataTable>
			</h:panelGroup>
		</h:form>
	</ui:define>
</ui:composition>

</html>