test-web/src/main/java/testas/mbeans/EntityController.java
package testas.mbeans;

import java.io.Serializable;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.DataModel;

import org.primefaces.context.RequestContext;
import org.primefaces.event.SelectEvent;

import testas.entities.EntityId;
import testas.mbeans.util.EntitiesDataModel;
import testas.mbeans.util.JsfUtil;
import testas.services.EntityFacadeLocal;

public abstract class EntityController<T extends EntityId> implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7791111183104724547L;

	private static final Logger LOGGER = Logger.getLogger(EntityController.class.getName());

	private static final ResourceBundle BUNDLE = ResourceBundle.getBundle("/Bundle");

	private EntitiesDataModel<T> items = null;
	private final Class<T> entityClass;

	private int selectedItemIndex;

	private boolean inlineEditingEnabled = false;

	private T selected;
	private T editing;

	public EntityController(Class<T> entityClass) {
		this.entityClass = entityClass;
	}

	// State properties

	public T getSelected() {
		// if (current == null) {
		// current = newEntityInstance();
		// }
		return selected;
	}

	public void setSelected(T newVal) {
		selected = newVal;
	}

	public boolean isEmptySelection() {
		return selected == null;
	}

	public boolean isSelectionEmpty() {
		return getSelected() == null || getSelected().getId() == null;
	}

	public boolean isInlineEditingEnabled() {
		return inlineEditingEnabled;
	}

	public void setInlineEditingEnabled(boolean inlineEditingEnabled) {
		this.inlineEditingEnabled = inlineEditingEnabled;
	}

	public T getEntity(java.lang.Long id) {
		return getFacade().find(id);
	}

	public DataModel<T> getItems() {
		if (items == null) {
			items = new EntitiesDataModel<T>(getFacade());
			if (selectedItemIndex >= 0)
				items.setRowIndex(selectedItemIndex);
		}
		return items;
	}

	public T getEditing() {
		return editing;
	}

	public void setEditing(T editing) {
		this.editing = editing;
	}

	// Actions
	public String prepareList() {
		if (editing!=null) editing = null;
		recreateModel();
		return "List";
	}

	public String prepareView() {
		return "View";
	}

	public String prepareCreate() {
//		setSelected();
		setEditing(newEntityInstance());
		return "Create";
	}
	public String prepareEdit() {
		setEditing(getSelected());
		return "Edit";
	}

	public void prepareInlineCreate() {
		setSelected(newEntityInstance());
		setEditing(getSelected());
		items = new EntitiesDataModel<T>(getEditing(), getFacade());
		items.setRowIndex(0);
		inlineEditingEnabled = true;
	}
	public void prepareInlineEdit() {
		setEditing(getSelected());
		inlineEditingEnabled = true;
		
	}


	public String create() {
		return createEntity() ? prepareCreate() : null;
	}


	public String update() {
		return updateEntity() ? "View" : null;
	}

	public String destroy() {
		performDestroy();
		recreateModel();
		return "List";
	}

	public String destroyAndView() {
		selectedItemIndex = items.getRowIndex();
		performDestroy();
		recreateModel();
		updateCurrentItem();
		if (selectedItemIndex >= 0) {
			return "View";
		} else {
			// all items were removed - go back to list
			recreateModel();
			return "List";
		}
	}

	private void performDestroy() {
		try {
			getFacade().remove(selected);
			JsfUtil.addSuccessMessage(BUNDLE.getString(entityClass.getSimpleName() + "Deleted"));
		} catch (Exception e) {
			JsfUtil.addErrorMessage(e, BUNDLE.getString("PersistenceErrorOccured"));
		}
	}

	private void updateCurrentItem() {
		int count = getFacade().count();
		if (selectedItemIndex >= count) {
			// selected index cannot be bigger than number of items:
			selectedItemIndex = count - 1;
		}
		if (items != null) {
			items.setRowIndex(selectedItemIndex);
		}
		setSelected(selectedItemIndex >= 0
				? getFacade().findRange(selectedItemIndex, 1).get(0)
				: null);
	}

	

	public void cancelInlineEdits() {
		if (getEditing() != null && (getEditing().getId() == null || -1l == getEditing().getId())) {
			recreateModel();
		}
		setEditing(null);
		inlineEditingEnabled = false;
		JsfUtil.addSuccessMessage(BUNDLE.getString(entityClass.getSimpleName()),
				BUNDLE.getString(entityClass.getSimpleName() + "Canceled"));
	}

	public void updateInlineEdits() {
		boolean isNew = isNewEditingItem();
		boolean updated = isNew ? createEntity() : updateEntity();
		if (updated) {
			if (isNew)
				recreateModel();
			inlineEditingEnabled = false;
		} else {
			selected = getEditing();
			inlineEditingEnabled = true;
		}
	}
	
	public void refresh() {
		setSelected(null);
		recreateModel();
	}

	// Event callbacks

	public void onRowSelect(SelectEvent event) {
		if (inlineEditingEnabled) {
			RequestContext.getCurrentInstance().execute("PF('rowEditingConfirm').show();");
			inlineEditingEnabled = false;
		}
	}

	// Utility methods
	public boolean isNewEditingItem() {
		return getEditing().getId() == null || getEditing().getId() < 0;
	}

	protected boolean createEntity() {
		try {
			if (getEditing().getId() != null)
				getEditing().setId(null);
			getFacade().create(getEditing());
			JsfUtil.addSuccessMessage(BUNDLE.getString(entityClass.getSimpleName()),
					BUNDLE.getString(entityClass.getSimpleName() + "Created"));
			return true;
		} catch (Exception e) {
			JsfUtil.addErrorMessage(e, BUNDLE.getString("PersistenceErrorOccured"));
			return false;
		}
	}

	public boolean updateEntity() {
		try {
			getFacade().edit(getEditing());
			JsfUtil.addSuccessMessage(BUNDLE.getString(entityClass.getSimpleName()),
					BUNDLE.getString(entityClass.getSimpleName() + "Updated"));
			return true;
		} catch (Exception e) {
			JsfUtil.addErrorMessage(e, BUNDLE.getString("PersistenceErrorOccured"));
			return false;
		}
	}

	private void recreateModel() {
		items = null;
	}

	public boolean inlineEditable(T item) {
		return selected != null && item != null && inlineEditingEnabled && item.getId() != null
				&& item.getId().equals(selected.getId());
	}

	public boolean inlineNewEditable(T item) {
		return selected != null && item != null && inlineEditingEnabled && item.getId() != null
				&& item.getId().equals(selected.getId()) && -1l == item.getId();
	}

	protected T newEntityInstance() {
		try {
			T ret = entityClass.newInstance();
			ret.setId(-1l);
			return ret;
		} catch (InstantiationException ex) {
			LOGGER.log(Level.SEVERE, null, ex);
			throw new RuntimeException(ex);
		} catch (IllegalAccessException ex) {
			LOGGER.log(Level.SEVERE, null, ex);
			throw new RuntimeException(ex);
		}
	}

	protected abstract EntityFacadeLocal<T> getFacade();

	// Converter for entity 
	public static class EntityControllerConverter implements Converter {

		private final String entityControllerName;

		public EntityControllerConverter(String entityControllerName) {
			this.entityControllerName = entityControllerName;
		}

		@Override
		public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
			if (value == null || value.length() == 0) {
				return null;
			}

			@SuppressWarnings("rawtypes")
			EntityController controller = (EntityController) facesContext.getApplication().getELResolver()
					.getValue(facesContext.getELContext(), null, entityControllerName);
			if ("-1".equals(value)) {
				System.out.println("Retrieving selection for -1");
				Thread.dumpStack();
			}
			return controller.getEntity(getKey(value));
		}

		java.lang.Long getKey(String value) {
			java.lang.Long key;
			key = Long.valueOf(value);
			return key;
		}

		String getStringKey(java.lang.Long value) {
			return Long.toString(value, 10);
		}

		@Override
		public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
			if (object == null) {
				return null;
			}
			if (object instanceof EntityId) {
				EntityId o = (EntityId) object;
				return getStringKey(o.getId());
			} else if (object instanceof Long) {
				Long l = ((Long) object);
				return Long.toString(l, 10);
			} else {
				throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName()
						+ "; expected type: " + EntityId.class.getName());
			}
		}

	}

}

test-web/src/main/java/testas/mbeans/TeamEntityController.java
package testas.mbeans;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.convert.FacesConverter;
import javax.inject.Named;

import org.primefaces.model.DualListModel;

import testas.entities.LeagueEntity;
import testas.entities.TeamEntity;
import testas.services.LeagueEntityFacadeLocal;
import testas.services.TeamEntityFacadeLocal;

@Named("teamEntityController")
@SessionScoped
public class TeamEntityController extends EntityController<TeamEntity> {
	
	private List<LeagueEntity> leagues;
	/**
	 * 
	 */
	private static final long serialVersionUID = -6046685050686569878L;
	@EJB
	private TeamEntityFacadeLocal ejbFacade;
	@EJB
	private LeagueEntityFacadeLocal leaguesFacade;

	private DualListModel<LeagueEntity> leaguesDl;

	public TeamEntityController() {
		super(TeamEntity.class);
	}

	protected TeamEntityFacadeLocal getFacade() {
		return ejbFacade;
	}

	@Override
	public String prepareCreate() {
		String ret = super.prepareCreate();
		getEditing().setLeagues(new HashSet<LeagueEntity>());
		List<LeagueEntity> src = Collections.<LeagueEntity> emptyList();
		List<LeagueEntity> target = new ArrayList<LeagueEntity>();
		leaguesDl = new DualListModel<LeagueEntity>(src, target);
		return ret;
	}

	@Override
	public String prepareEdit() {
		String ret = super.prepareEdit();
		List<LeagueEntity> src = leaguesFacade.getLeagues(getEditing().getGame());
		List<LeagueEntity> target = new ArrayList<LeagueEntity>(ejbFacade.getLeagues(getSelected().getId()));
		src.removeAll(target);
		leaguesDl = new DualListModel<LeagueEntity>(src, target);
		return ret;
	}

	@Override
	public void setSelected(TeamEntity newVal) {
		leaguesDl = null;
		leagues = null;
		super.setSelected(newVal);
	}
	
	public List<LeagueEntity> getLeagues() {
		if (leagues == null) {
			if (getEditing()!=null && getEditing().getId()!=null) {
				leagues = ejbFacade.getLeagues(getEditing().getId());
			} else {
				leagues = Collections.emptyList();
			}
		}
		return leagues;
	}
	
	public void gameValueChanged() {
		if (getEditing().getId() != null && -1l != getEditing().getId()) {
			throw new IllegalStateException("Updating game on already created team");
		}
		List<LeagueEntity> src = getEditing().getGame() == null ? Collections.<LeagueEntity> emptyList()
				: leaguesFacade.getLeagues(getEditing().getGame());

		leaguesDl = new DualListModel<LeagueEntity>(src, new ArrayList<LeagueEntity>());

	}

	public DualListModel<LeagueEntity> getLeaguesDualList() {
		return leaguesDl;
	}

	public void setLeaguesDualList(DualListModel<LeagueEntity> dl) {
		this.leaguesDl = dl;
	}

	@Override
	public String create() {
		getEditing().getLeagues().addAll(leaguesDl.getTarget());
		getEditing().getLeagues().retainAll(leaguesDl.getTarget());
		return super.create();
	}
	
	@Override
	public String update() {
		getEditing().setLeagues(new HashSet<>(leaguesDl.getTarget()));
		return super.update();
	}
	
	@FacesConverter(forClass = TeamEntity.class)
	public static class TeamEntityControllerConverter extends EntityControllerConverter {

		public TeamEntityControllerConverter() {
			super("teamEntityController");
		}

	}

}

test-web/src/main/webapp/teamEntity/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/template.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.CreateTeamEntityTitle}"></h:outputText>
	</ui:define>
	<ui:define name="body">
		<h:form>
			<p:growl id="growl" showDetail="true" sticky="false" />
			<p:toolbar>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:button outcome="/index" value="#{bundle.IndexLink}" />
					<p:commandButton action="#{teamEntityController.prepareList}"
						value="#{bundle.ShowAllLink}" immediate="true" json="false" />
				</p:toolbarGroup>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:commandButton action="#{teamEntityController.create}"
						value="#{bundle.SaveLink}" json="false" process="@all"
						update="growl, game, name, leagues, playedGames" />
				</p:toolbarGroup>
			</p:toolbar>

			<h:panelGrid columns="2">
				<p:outputLabel value="#{bundle.Label_name}" for="name" />
				<p:inputText id="name" value="#{teamEntityController.editing.name}"
					title="#{bundle.Title_name}" required="true"
					requiredMessage="#{bundle.RequiredMessage_name}" />
				<p:outputLabel value="#{bundle.Label_game}" for="game" />

				<p:selectOneMenu id="game"
					value="#{teamEntityController.editing.game}" required="true"
					requiredMessage="#{bundle.RequiredMessage_game}">
					<p:ajax listener="#{teamEntityController.gameValueChanged}"
						update="game leagues" />

					<f:selectItem itemLabel="#{bundle.SelectGameType}" itemValue="" />
					<f:selectItem itemLabel="#{bundle.BASKETBALL}"
						itemValue="BASKETBALL" />
					<f:selectItem itemLabel="#{bundle.FOOTBALL}" itemValue="FOOTBALL" />
				</p:selectOneMenu>

				<p:outputLabel value="#{bundle.Label_playedGames}" for="playedGames" />
				<p:inputText id="playedGames"
					value="#{teamEntityController.editing.playedGames}"
					title="#{bundle.Title_playedGames}" required="true"
					requiredMessage="#{bundle.RequiredMessage_playedGames}" />
			</h:panelGrid>

			<h:panelGroup>
				<p:outputLabel value="#{bundle.Label_Leagues}" for="leagues" />
				<p:pickList id="leagues"
					value="#{teamEntityController.leaguesDualList}" var="league"
					itemLabel="#{league.name}" itemValue="#{league.id}" converter="leagueConverter"/>
				
			</h:panelGroup>
		</h:form>
	</ui:define>
</ui:composition>

</html>

test-web/src/main/webapp/teamEntity/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/template.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.EditTeamEntityTitle}"></h:outputText>
	</ui:define>
	<ui:define name="body">
		<h:form>
			<p:growl id="growl" showDetail="true" sticky="false" />
			<p:toolbar>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:button outcome="/index" value="#{bundle.IndexLink}" />
					<p:commandButton action="#{teamEntityController.prepareList}"
						value="#{bundle.ShowAllLink}" />
				</p:toolbarGroup>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:button outcome="View" value="#{bundle.ViewLink}" />
					<p:commandButton action="#{teamEntityController.update}"
						value="#{bundle.SaveLink}"
						update="growl, name, leagues, playedGames" />
				</p:toolbarGroup>
			</p:toolbar>

			<h:panelGrid columns="2">
				<p:outputLabel value="#{bundle.Label_id}" />
				<h:outputText value="#{teamEntityController.editing.id}"
					title="#{bundle.Title_id}" />

				<p:outputLabel value="#{bundle.Label_name}" for="name" />
				<p:inputText id="name" value="#{teamEntityController.editing.name}"
					title="#{bundle.Title_name}" required="true"
					requiredMessage="#{bundle.RequiredMessage_name}" />

				<p:outputLabel value="#{bundle.Label_game}" />
				<h:outputText value="#{bundle[teamEntityController.editing.game]}"
					title="#{bundle.Title_game}" />

				<p:outputLabel value="#{bundle.Label_playedGames}" for="playedGames" />
				<p:inputText id="playedGames"
					value="#{teamEntityController.editing.playedGames}"
					title="#{bundle.Title_playedGames}" required="true"
					requiredMessage="#{bundle.RequiredMessage_playedGames}" />
			</h:panelGrid>
			<h:panelGroup>
				<p:outputLabel value="#{bundle.Label_Leagues}" for="leagues" />
				<p:pickList id="leagues"
					value="#{teamEntityController.leaguesDualList}" var="league"
					itemLabel="#{league.name}" itemValue="#{league.id}"
					converter="leagueConverter" />

			</h:panelGroup>
		</h:form>
	</ui:define>
</ui:composition>

</html>

test-web/src/main/webapp/teamEntity/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/template.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.ListTeamEntityTitle}"></h:outputText>
	</ui:define>
	<ui:define name="body">
		<h:form styleClass="jsfcrud_list_form" id="form">
			<p:growl id="growl" showDetail="true" sticky="false" />
			<p:toolbar id="workGroupToolbar">
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:button outcome="/index" value="#{bundle.IndexLink}" />
				</p:toolbarGroup>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:commandButton action="#{teamEntityController.prepareView}"
						value="#{bundle.ViewLink}" ajax="false"
						disabled="#{teamEntityController.selectionEmpty || teamEntityController.inlineEditingEnabled}" />

					<p:commandButton action="#{teamEntityController.prepareCreate}"
						value="#{bundle.CreateLink}" ajax="false"
						disabled="#{teamEntityController.inlineEditingEnabled}" />


					<p:commandButton action="#{teamEntityController.prepareEdit}"
						value="#{bundle.EditLink}" ajax="false"
						disabled="#{teamEntityController.selectionEmpty || teamEntityController.inlineEditingEnabled}" />


					<p:commandButton action="#{teamEntityController.destroy}"
						value="#{bundle.DestroyLink}" ajax="false" update="growl"
						disabled="#{teamEntityController.selectionEmpty || teamEntityController.inlineEditingEnabled}" />

				</p:toolbarGroup>
				<p:toolbarGroup id="inlineToolbarGroup">
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:commandButton
						action="#{teamEntityController.prepareInlineCreate}"
						disabled="#{teamEntityController.inlineEditingEnabled}"
						value="#{bundle.CreateInlineLink}" ajax="true"
						update="datatable workGroupToolbar" />
					<p:commandButton action="#{teamEntityController.prepareInlineEdit}"
						value="#{bundle.EditInlineLink}"
						disabled="#{teamEntityController.selectionEmpty || teamEntityController.inlineEditingEnabled}"
						update="datatable workGroupToolbar" />
					<p:commandButton action="#{teamEntityController.cancelInlineEdits}"
						value="#{bundle.CancelInlineLink}" immediate="true"
						disabled="#{!teamEntityController.inlineEditingEnabled}"
						update="workGroupToolbar growl datatable" />
					<p:commandButton action="#{teamEntityController.updateInlineEdits}"
						value="#{bundle.UpdateInlineLink}"
						disabled="#{!teamEntityController.inlineEditingEnabled}"
						update="workGroupToolbar growl datatable" />
				</p:toolbarGroup>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:commandButton action="#{teamEntityController.refresh}"
						value="#{bundle.RefreshLink}" update="workGroupToolbar datatable"
						disabled="#{teamEntityController.inlineEditingEnabled}" />
				</p:toolbarGroup>

			</p:toolbar>

			<h:panelGroup>
				<p:dataTable id="datatable" widgetVar="datatable"
					value="#{teamEntityController.items}" var="item"
					selection="#{teamEntityController.selected}" selectionMode="single"
					rows="10" paginator="true" lazy="true"
					paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
					rowsPerPageTemplate="5,10,15">
					<p:ajax event="rowSelect"
						listener="#{teamEntityController.onRowSelect}"
						update=":form:workGroupToolbar, :form:datatable" />

					<p:column headerText="#{bundle.Title_id}" style="width: 100px">
						<h:outputText value="#{item.id}" />
					</p:column>
					<p:column headerText="#{bundle.Title_name}">
						<h:outputText value="#{item.name}"
							rendered="#{!teamEntityController.inlineEditable(item)}" />
						<p:inputText id="name"
							value="#{teamEntityController.editing.name}"
							title="#{bundle.Title_name}" required="true"
							requiredMessage="#{bundle.RequiredMessage_name}"
							rendered="#{teamEntityController.inlineEditable(item)}" />
					</p:column>
					<p:column headerText="#{bundle.Title_game}">
						<h:outputText value="#{bundle[item.game]}"
							rendered="#{!teamEntityController.inlineNewEditable(item)}" />
						<p:selectOneMenu id="game"
							rendered="#{teamEntityController.inlineNewEditable(item)}"
							value="#{teamEntityController.editing.game}" required="true"
							requiredMessage="#{bundle.RequiredMessage_game}">
							<f:selectItem itemLabel="#{bundle.SelectGameType}" itemValue="" />
							<f:selectItem itemLabel="#{bundle.BASKETBALL}"
								itemValue="BASKETBALL" />
							<f:selectItem itemLabel="#{bundle.FOOTBALL}" itemValue="FOOTBALL" />
						</p:selectOneMenu>
					</p:column>
					<p:column headerText="#{bundle.Title_playedGames}">
						<h:outputText value="#{item.playedGames}"
							rendered="#{!teamEntityController.inlineEditable(item)}" />
						<p:spinner value="#{teamEntityController.editing.playedGames}"
							min="0" rendered="#{teamEntityController.inlineEditable(item)}" />
					</p:column>
				</p:dataTable>
			</h:panelGroup>
		</h:form>
	</ui:define>
</ui:composition>

</html>

test-web/src/main/webapp/teamEntity/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/template.xhtml">
	<ui:define name="title">
		<h:outputText value="#{bundle.ViewTeamEntityTitle}"></h:outputText>
	</ui:define>
	<ui:define name="body">
		<h:form>
			<p:growl id="growl" showDetail="true" sticky="false" />
			<p:toolbar>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:button outcome="/index" value="#{bundle.IndexLink}" />
					<p:commandButton action="#{leagueEntityController.prepareList}"
						value="#{bundle.ShowAllLink}" ajax="false" />
				</p:toolbarGroup>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:commandButton action="#{leagueEntityController.prepareCreate}"
						value="#{bundle.CreateLink}" ajax="false" />
					<p:button outcome="Edit" value="#{bundle.EditLink}" />
				</p:toolbarGroup>
				<p:toolbarGroup>
					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>
					<p:commandButton action="#{leagueEntityController.destroyAndView}"
						value="#{bundle.DestroyLink}" ajax="false" />
				</p:toolbarGroup>
			</p:toolbar>
			<h:panelGrid columns="2">
				<h:outputText value="#{bundle.Label_id}" />
				<h:outputText value="#{teamEntityController.selected.id}"
					title="#{bundle.Title_id}" />
				<h:outputText value="#{bundle.Label_name}" />
				<h:outputText value="#{teamEntityController.selected.name}"
					title="#{bundle.Title_name}" />
				<h:outputText value="#{bundle.Label_game}" />
				<h:outputText value="#{teamEntityController.selected.game}"
					title="#{bundle.Title_game}" />
				<h:outputText value="#{bundle.Label_playedGames}" />
				<h:outputText value="#{teamEntityController.selected.playedGames}"
					title="#{bundle.Title_playedGames}" />
			</h:panelGrid>
			<br />
			<p:dataTable value="#{teamEntityController.leagues}" var="item">
				<p:column headerText="#{bundle.Title_id}">
					<h:outputText value="#{item.id}" />
				</p:column>
				<p:column headerText="#{bundle.Title_name}">
					<h:outputText value="#{item.name}" />
				</p:column>
			</p:dataTable>

		</h:form>
	</ui:define>
</ui:composition>

</html>